### ISSUE TITLE
Retina ArrowUp & ArrowDown

### ISSUE THREAD

**Issue by baptistebriel** [siamakmokhtari/licon#4]
Hello,

Take a look to thoses screenshots : the icons ArrowUp & ArrowDown are looking strange on my Retina MBP. (It does not affect ArrowLeft & ArrowRight.)

Here's the current code :

``` css
.licon-arrowup:before{
     left: 8px;
}
.licon-arrowdown:before{
     left: 8px;
}
```

![capture decran 2014-06-20 a 11 24 24](https://cloud.githubusercontent.com/assets/2464663/3338504/c217ea10-f85c-11e3-8816-135b1951d693.png)

![capture decran 2014-06-20 a 11 24 44](https://cloud.githubusercontent.com/assets/2464663/3338506/c6f0fc02-f85c-11e3-8ae4-dbafbff3d109.png)

Perhaps you'll need to target it only on retina devices.

``` css
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
     .licon-arrowup:before{
          left: 10px;
     }
     .licon-arrowdown:before{
          left: 10px;
     }
}
```

I don't use SASS, but here's an idea how to make this using LESS.

``` css
@media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
    /* i.licon-arrowup */
    .licon-arrowup{
        &:before{
            left: @size/4 + 2;
        }
    }

    /* i.licon-arrowdown */
    .licon-arrowdown{
        &:before{
            left: @size/4 + 2;
        }
    }
}
```

This is very strange because the :after has "right: 10px;", so left should be the same. How does it looks on normal screens ?
Have a nice day.
